name: "Bug Report"
description: "Report a bug with the library template."
title: "Describe the bug"
labels: ["bug"]
body:
  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the bug"
      placeholder: "Provide a clear description of the bug."
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to reproduce"
      placeholder: "List the steps to reproduce the issue."
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      placeholder: "Describe what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual behavior"
      placeholder: "Describe what actually happened."
    validations:
      required: true
