name: Deploy PR preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    concurrency: preview-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build website
        if: github.event.action != 'closed'
        run: mkdocs build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
